name: Build

on:
    push:
    release:
        types: [published]

jobs:
    main:
        name: Build
        runs-on: ubuntu-22.04
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v3
            - name: "Setup Java"
              uses: actions/setup-java@v3
              with:
                distribution: "temurin"
                java-version: "11"
            - name: "Setup wasm-pack"
              uses: jetli/wasm-pack-action@v0.4.0
              with:
                version: "latest"
            - name: "Build All"
              run: ./gradlew build