name: Ready for Release

on:
    workflow_dispatch:
    push:
      branches-ignore:
        - main

jobs:
    main:
        name: ReleaseReady
        runs-on: ubuntu-22.04
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v3
            - name: "Setup Java"
              uses: actions/setup-java@v3
              with:
                distribution: "temurin"
                java-version: "11"
            - name: "Validate Gradle wrapper"
              uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
            - name: "Check Minor Bump"
              uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
              with:
                arguments: check_minor_bump
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}