name: Upload Package

on:
    workflow_dispatch:
    push:
        branches:
            "main"

jobs:
    main:
        name: Release
        runs-on: ubuntu-22.04
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v3
            - name: "Setup Java"
              uses: actions/setup-java@v3
              with:
                distribution: "temurin"
                java-version: "11"
            - name: "Setup wasm-pack"
              uses: jetli/wasm-pack-action@v0.4.0
              with:
                version: "latest"
            - name: "Validate Gradle wrapper"
              uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
            - name: "Publish package"
              uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
              with:
                arguments: publish
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}